name: aoc2017
version: '0.1.0.0'
synopsis: Advent of Code solutions for 2017 (adventofcode.com/2017)
description: Please see the README on Github at <https://git.2nd.io/anup/aoc2017#readme>
category: Web
author: Anup Kishore
maintainer: anup@secondspectrum.com
copyright: 2017 Anup Kishore
license: BSD3
homepage: https://git.2nd.io/anup/aoc2017#readme
git: https://git.2nd.io/anup/aoc2017

extra-source-files:
- README.md

dependencies:
- base >=4.7 && <5
- text >=1.2.2.0
- containers
ghc-options: [-Wall, -Wwarn]

library:
  source-dirs: src
  other-modules:
  - Paths_aoc2017

data-files:
  - data/*

executables:
  day-1: &base-exe
    main: Main
    source-dirs: day1
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N]
    other-modules:
    - Paths_aoc2017
    dependencies:
    - aoc2017
  day-2:
    <<: *base-exe
    source-dirs: day2
  day-3: &fast-exe
    <<: *base-exe
    ghc-options: [ -threaded, -rtsopts, -with-rtsopts=-N, -O2]
    source-dirs: day3
  day-4:
    <<: *base-exe
    source-dirs: day4
  day-5:
    <<: *fast-exe
    source-dirs: day5
  day-6:
    <<: *base-exe
    source-dirs: day6


tests:
  day-1-test:
    main: Spec.hs
