name: aoc2018
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/anup-2s/advent-of-code
license: BSD3
author: Anup Kishore
maintainer: anup.kishore@gmail.com
copyright: 2018 Anup Kishore
category: Web

extra-source-files:
  - README.md

data-files:
  - data/day*/p*

ghc-options:
  - -Wall
  - -Werror
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-type-defaults

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - MultiWayIf
  - TupleSections
  - DeriveGeneric
  - RankNTypes

_base-internal-lib: &LIB
  other-modules:
    - Paths_aoc2018
  dependencies:
    - aoc2018

_base-exe: &BASE_EXE
  main: Main
  ghc-options: [-threaded, -rtsopts, -with-rtsopts=-N, -O2]

dependencies:
  - base >= 4.7 && < 5
  - text >=1.2.2.0
  - megaparsec

library:
  source-dirs: src
  other-modules:
    - Paths_aoc2018

internal-libraries:
  l-day1: &LIB1
    <<: *LIB
    source-dirs: day1
    dependencies:
      - aoc2018
      - containers
  l-day2: &LIB2
    <<: *LIB
    source-dirs: day2

executables:
  day1:
    <<: *BASE_EXE
    <<: *LIB1
  day2:
    <<: *BASE_EXE
    <<: *LIB2

tests:
  all-tests:
    defaults: hspec/hspec@master
    dependencies:
      - name: l-day1
        mixin: (Main as Day1)
      - name: l-day2
        mixin: (Main as Day2)
